import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Sparkles, Calendar as CalendarIcon, Save, Printer } from "lucide-react";
import DashboardShell from "../../../components/DashboardShell.jsx";
import { api } from "../../../lib/api.js";

export default function ExamScheduler() {
  const [classLevel, setClassLevel] = useState("");
  const [startDate, setStartDate] = useState("");
  const [loading, setLoading] = useState(false);
  const [schedule, setSchedule] = useState(null);

  const { data: subjects } = useQuery({
    queryKey: ["subjects"],
    queryFn: () => api.get("/students/subjects").then((r) => r.data.subjects),
  });

  const handleGenerate = async () => {
    if (!classLevel || !startDate) {
      alert("Please select a class and start date.");
      return;
    }
    setLoading(true);
    try {
      // Pick random 5 subjects for the schedule
      const selectedSubjects = (subjects || []).sort(() => 0.5 - Math.random()).slice(0, 5).map(s => s.name);
      
      const res = await api.post("/ai/exam-schedule", {
        className: classLevel,
        subjects: selectedSubjects,
        startDate
      });
      setSchedule({
        className: classLevel,
        data: res.data.schedule
      });
    } catch (err) {
      alert("Failed to generate schedule.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardShell>
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-display font-bold text-indigo-900">AI Exam Scheduler</h1>
          <p className="text-sm text-indigo-600 mt-1">Generate optimal date-sheets with smart gap days.</p>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Configuration Panel */}
        <div className="lg:col-span-1 bg-white p-6 rounded-2xl shadow-sm border border-indigo-50">
          <h2 className="text-lg font-bold text-indigo-900 mb-4 flex items-center gap-2">
            <Sparkles className="text-marigold-500" /> AI Parameters
          </h2>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm text-gray-600 mb-1">Target Class</label>
              <select value={classLevel} onChange={e => setClassLevel(e.target.value)} className="w-full border border-gray-200 rounded-lg px-3 py-2 bg-white">
                <option value="">Select Class</option>
                <option value="Class 8">Class 8</option>
                <option value="Class 9">Class 9</option>
                <option value="Class 10">Class 10</option>
                <option value="Class 12">Class 12</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm text-gray-600 mb-1">Start Date</label>
              <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="w-full border border-gray-200 rounded-lg px-3 py-2" />
            </div>

            <div className="pt-2">
              <button onClick={handleGenerate} disabled={loading} className="w-full bg-indigo-600 text-white font-medium px-4 py-2.5 rounded-xl hover:bg-indigo-700 transition flex items-center justify-center gap-2 disabled:opacity-50">
                {loading ? "Generating..." : "Generate Date-Sheet"} <Sparkles size={16} />
              </button>
            </div>
            
            <div className="bg-indigo-50 p-4 rounded-xl mt-4">
              <p className="text-xs text-indigo-800 leading-relaxed">
                <strong>How it works:</strong> The AI engine distributes subjects starting from the selected date, automatically allocating a 3-day gap for difficult subjects (e.g. Science, Maths) and skipping Sundays.
              </p>
            </div>
          </div>
        </div>

        {/* Results Panel */}
        <div className="lg:col-span-2">
          {schedule ? (
            <div className="bg-white rounded-2xl shadow-sm border border-indigo-50 overflow-hidden">
              <div className="bg-indigo-600 p-6 text-white flex justify-between items-center">
                <div>
                  <h2 className="text-xl font-display font-bold">Term Examination Date-Sheet</h2>
                  <p className="text-indigo-200 text-sm mt-1">For {schedule.className} • Generated by AI</p>
                </div>
                <div className="flex gap-2">
                  <button onClick={() => window.print()} className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition" title="Print">
                    <Printer size={18} />
                  </button>
                  <button className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition" title="Save & Publish">
                    <Save size={18} />
                  </button>
                </div>
              </div>
              <div className="p-0">
                <table className="w-full text-left text-sm">
                  <thead className="bg-gray-50 border-b border-gray-100 text-gray-500 uppercase tracking-wider text-[11px] font-bold">
                    <tr>
                      <th className="p-4">Date</th>
                      <th className="p-4">Day</th>
                      <th className="p-4">Time</th>
                      <th className="p-4">Subject</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {schedule.data.map((item, i) => {
                      const d = new Date(item.date);
                      const dayName = d.toLocaleDateString('en-US', { weekday: 'long' });
                      const dateStr = d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
                      
                      return (
                        <tr key={i} className="hover:bg-gray-50 transition">
                          <td className="p-4 font-medium text-gray-900">{dateStr}</td>
                          <td className="p-4 text-gray-600">{dayName}</td>
                          <td className="p-4 text-gray-600">{item.time}</td>
                          <td className="p-4">
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full font-medium bg-indigo-50 text-indigo-700">
                              {item.subject}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          ) : (
            <div className="h-full bg-white/50 border-2 border-dashed border-indigo-100 rounded-2xl flex flex-col items-center justify-center p-12 text-center">
              <CalendarIcon size={48} className="text-indigo-200 mb-4" />
              <h3 className="text-lg font-bold text-gray-900 mb-2">No Schedule Generated</h3>
              <p className="text-gray-500 max-w-sm">Select a class and start date on the left to let the AI build an optimal examination date-sheet.</p>
            </div>
          )}
        </div>
      </div>
    </DashboardShell>
  );
}
